insert into Restaurant (id, name, address) values (1, 'Restaurant Trebbiano', 'Alameda Campinas, 266 - Cerqueira César, São Paulo - SP')
insert into Restaurant (id, name, address) values (2, 'ARABEK', 'R. Pamplona, 684 - Jardim Paulista, São Paulo - SP')
insert into Restaurant (id, name, address) values (3, 'Temakeria Makis Place', 'Alameda Santos, 1202 - Jardim Paulista, São Paulo - SP')
insert into Restaurant (id, name, address) values (4, 'Spot', 'Alameda Min. Rocha Azevedo, 72 - Bela Vista, São Paulo - SP')
insert into Restaurant (id, name, address) values (5, 'Noah Gastronomia', 'Rua Peixoto Gomide, 707 - Cerqueira César, São Paulo - SP')
insert into Restaurant (id, name, address) values (6, 'Seen - Restaurant & Bar', 'Alameda Santos, 1437 - Jardim Paulista, São Paulo - SP')
insert into Restaurant (id, name, address) values (7, 'Restaurante Pamplona', 'R. Pamplona, 900 - Jardim Paulista, São Paulo - SP')
insert into Restaurant (id, name, address) values (8, 'Capim Santo São Paulo', 'Alameda Min. Rocha Azevedo, 471 - Jardins, São Paulo - SP')
insert into Restaurant (id, name, address) values (9, 'Manai Gastronomia', 'Alameda Santos, 1219 - Cerqueira César, São Paulo - SP')
insert into Restaurant (id, name, address) values (10, 'Pimenta Rosa', 'Alameda Santos, 831 - Jardim Paulista, São Paulo - SP')
insert into Restaurant (id, name, address) values (11, 'Abbraccio', 'Avenida Paulista, 2064 Shopping Center 3 - Bela Vista, São Paulo - SP')
insert into Restaurant (id, name, address) values (12, 'Club Life To Go Paulista', 'Alameda Santos, 1518 - Lojas 71/72 - Jardim Paulista, São Paulo - SP')

insert into Feedback (id, preference, satisfied, comment, restaurantId) values (1, 'Vegetariano', true, 'O restaurante tem uma ótima comida vegetariana!', 1)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (2, 'Vegetariano', true, 'Ambiente aconchegante, funcionários atenciosos e comida vegetariana fresquinha.', 1)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (3, 'Vegetariano', false, 'O restaurante se diz vegetariano, mas tem mais prato com carne do que vegetariano.', 1)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (4, 'petfriendly', true, 'Adorei o restaurante e ainda tem um espaço legal para deixar o pet.', 1)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (5, 'petfriendly', true, 'A comida é muito boa, e além de ter espaço para pet tem um cardápio de comidinhas e petiscos para pet.', 1)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (6, 'petfriendly', false, 'O ambiente para petfriendly do qual o restaurante diz ter, não tem tanta estrutura para pets.', 2)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (7, 'petfriendly', false, 'O restaurante fala que é petfriendly, mas o ambiente nem é tão amigável para pet. Não cumpre com o que diz', 2)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (8, 'petfriendly', false, 'Ambiente com cheiro ruim. Por ser petfriendly deveriam fazer a limpeza constante, não volto mais.', 2)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (9, 'petfriendly', true, 'Eu e meu pet fomos bem recebidos, e ele ganhou até um biscoito rs.', 2)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (10, 'vegano', true, 'Único restaurante que fui que tem comida vegana de qualidade. Ganharam um novo cliente fiel!', 3)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (11, 'vegetariano', true, 'Não sou vegetariano/vegano mas fui conhecer, e adorei a comida, vou voltar com certeza.', 3)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (12, 'vegano', false, 'Tem comida a base de Ovo, então não cumprem com o título de ser um restaurante vegano.', 3)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (13, 'kidfriendly', true, 'Comida de boa qualidade e de preço acessível, e ainda minha filha ficou se divertindo no parquinho do restaurante.', 4)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (14, 'kidfriendly', false, 'Restaurante caro, e ainda falei que meu sobrinho é alérgico a lactose, e mesmo assim deram a ele uma sobremesa a base de lactose, funcionários sem instruções, péssimo.', 4)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (15, 'vegetariano', false, 'Não gostei, eu peguei uma lasanha de abóbrinha e estava estragada. A comida não parece fresca.', 4)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (16, 'kidfriendly', false, 'Achei a comida boa, porém o banheiro não tem trocador, para trocar meu bebê foi bem ruim.', 4)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (17, 'intolerantelactose', true, 'Primeiro restaurante que tem sobremesa sem lactose, e tudo gostoso e fresquinho, amei!', 5)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (18, 'intolerantelactose', true, 'Os pratos sem lactose são maravilhosos, sou intolerante a lactose e amei, difícil achar restaurantes com essa categoria.', 5)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (19, 'vegano', true, 'Estava procurando um restaurante vegano, e conheci esse, adorei. A comida é deliciosa e fresquinha.', 5)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (20, 'intolerantelactose', false, 'Comi um pudim e passei muito mal depois, acho que o pudim foi feito com leite, estranho para um restaurante que diz ter comida para intolerantes a lactose.', 5)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (21, 'intolerantelactose', true, 'Estou a meses sem comer os doces que gosto por conta da minha intolerancia a lactose, até que conheci esse restaurante e tudo mudou. Comida vegana muito boa também', 5)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (22, 'intolerantelactose', true, 'Acho mais que válido deixar uma avaliação positiva para esse restaurante que possui comida muito boa e fresquinha, além de oferecer cardápio com váaarias opções para intolerantes a lactose o que é otimo!', 5)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (23, 'vegetariano', true, 'Restaurante cumpre com o que promete e ótimo custo benefício.', 6)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (24, 'vegetariano', false, 'Achei muito caro para o que oferecem.', 6)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (25, 'vegetariano', false, 'A comida é muito boa, porém o atendimento foi muito ruim e demorado, não sei se voltaria.', 6)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (26, 'vegetariano', true, 'Acho que precisam melhorar muito em questão de atendimento e agilidade, porém a comida vegana que oferecem é muito boa comparada com as da região, eu voltaria com certeza!', 6)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (27, 'vegetariano', true, 'Reclamam muito do atendimento, mas fui muito bem atendida, e a torta que peguei estava muito boa. Fora uns pratos veganos diferentes que eles tem que estavam com uma cara ótima!', 6)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (28, 'vegetariano', true, 'Restaurante maravilhoso. Dica, peguem um prato de carne louca que é feito de jaca, muito bom!', 6)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (29, 'petfriendly', true, 'Restaurante com preços acessiveis e com mesas na calçada onde pude ficar com meu pet', 7)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (30, 'petfriendly', true, 'Ambiente muito charmoso, possui área externa onde é possivel ficar com seu pet', 8)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (31, 'vegetariano', true, 'Restaurante possui uma boa quantidade de opções vegetarianas e também ótimas massas', 8)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (32, 'vegetariano', false, 'Não possui muitas opções vegetarianas, somente saladas', 9)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (33, 'kidfriendly', true, 'Ótimo para levar a família, as crianças, fora dos horários de pico é bem tranquilo e por ser self service tem muitas opções', 10)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (34, 'vegetariano', false, 'O self service tem muitas opções, mas opções vegetarianas são bem escassas, praticamente só saladas', 10)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (35, 'intolerantelactose', true, 'Para pessoas com intolerância a lactose tem muitos pratos e sobremesas sem leite, e todos muito saborosos. Só o atendimento que pode melhorar, os pratos demoram a chegar', 11)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (36, 'fit', false, 'As opções fits não são muito atrativas, não possui pratos diferentes do que se pode encontrar em outros restauntes com o preço bem mais barato', 12)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (37, 'restricaonozes', false, 'Fui para comer somente uma sobremesa, mas a maioria das opções são com nozes', 12)
insert into Feedback (id, preference, satisfied, comment, restaurantId) values (38, 'glutenfree', true, 'Encontrei muitos pratos sem gluten e deliciosos, tem diversas opções diferentes de outros restauntes', 12)
